web:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./:/var/www
    - ./Docker/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - php

php:
  image: nmcteam/php56
  volumes:
    - ./Docker/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./:/var/www
  links:
    - db
  expose:
    - 9000
   
db:
  image: sameersbn/mysql
  volumes:
   - ./Docker/mysql-data:/var/lib/mysql
  environment:
   - DB_NAME=spo
   - DB_USER=spo
   - DB_PASS=spo
  expose:
    - 3306
