version: '3'
services:
  php:
    build:
      context: './php/'
      args:
        - WITH_XDEBUG=true
    ports:
      - "9000:9000"
    volumes:
      - ../:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html/
      - ./logs:/var/log/docker
    container_name: apache
  db:
    image: mysql:latest
    restart: always
    volumes:
    - ./mysql-data:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - 3306
